homeassistant:
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret api_password
    - type: trusted_networks
      trusted_networks:
        - 172.29.4.4
        - 192.168.1.10

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
mobile_app:
discovery:
cloud:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensors.yaml
zone: !include zones.yaml

hassio:

# This enables HTML5 Push Notifications, set in the
notify:
#  - platform: html5
#    name: NOTIFIER_NAME
#    vapid_pub_key: YOUR_PUBLIC_KEY
#    vapid_prv_key: YOUR_PRIVATE_KEY
#    vapid_email: YOUR_EMAIL

# Removed/Disabled in my configuration.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
